### ISSUE TITLE
*only* send a certain set of logs to remote logging host

### ISSUE THREAD

**Issue by igalic** [saz/puppet-rsyslog#122]
currently, when sending a set of logs to a remote server, they will also end up in `/var/log/syslog`
```erb
# Sending logs that match <%= pattern %> to <%= host %> via <%= protocol_type %> on <%= port %> using <%=format_type %> format.
<%= pattern %> <%= protocol %><%= host %>:<%= port %><%= format %>
```

i've tried adding a horrible hack of appending "\n& ~" to `port`, but that ended up being broken, because of the comment :D

i'd like to be able to *only* send logs to the remote, since they already exist as files on the host
(i'm using imfiles to forward files to a central logstash server.)

What would be a good name to introduce here, that means, this `pattern` will only be sent to the remote host?

**Comment by saz** [comment]
Maybe host_only_pattern?

**Comment by saz** [comment]
Any news on this?

**Comment by igalic** [comment]
oy. i haven't touched / needed this in a while.
we solved our problem back then by configuring haproxy explicitly, and then later a log-shipper to pick up its log file.

**Comment by ubellavance** [comment]
@saz I think that this issue exists because of the default template, which contains this: `*.info;mail.none;authpriv.none;cron.none                /var/log/messages`. I think that if we had a way to specify a facility to exclude from this, it would probably solve the problem.  For example: you set your imfile to to use the local6 facility, and you set local6 as a facility to exclude from /var/log/messages, it would give something like this:
`*.info;mail.none;authpriv.none;cron.none;local6.none                /var/log/messages`.

**Comment by ubellavance** [comment]
Or maybe an action that would tell rsyslog to do nothing with the logs with this tag...

**Comment by ubellavance** [comment]
Like this (with facility), using hiera
```
rsyslog::client::log_filters:
  - expression: '$syslogfacility-text == "local6"'
    action: '~'
```
