### ISSUE TITLE
rsyslog doesn't start on centos7

### ISSUE THREAD

**Issue by JohnTheodore** [saz/puppet-rsyslog#142]
change from stopped to running failed: Could not start Service[rsyslog]: Execution of '/usr/bin/systemctl start rsyslog' returned 1: A dependency job for rsyslog.service failed. See 'journalctl -xn' for details.

^If I do 'systemctl enable rsyslog' everything is fixed and fine. I'm not sure what is causing this currently.

**Comment by saz** [comment]
Does this problem still exists?

**Comment by gaima8** [comment]
I can't talk for CentOS 7, but rsyslogd won't start Debian Jessie.
It's because rsyslogd 8.4.2 doesn't accept -c4 as an option anymore.

The man page says it'll ignore -c, but it really doesn't.


I choose to fix my problem like this;


Index: modules/rsyslog/manifests/params.pp
===================================================================
--- modules/rsyslog/manifests/params.pp (revision 350830)
+++ modules/rsyslog/manifests/params.pp (working copy)
@@ -31,7 +31,6 @@
       $rsyslog_d              = '/etc/rsyslog.d/'
       $rsyslog_conf           = '/etc/rsyslog.conf'
       $rsyslog_default        = '/etc/default/rsyslog'
-      $default_config_file    = 'rsyslog_default'
       $run_group              = 'root'
       $log_group              = 'adm'
       $log_style              = 'debian'
@@ -51,6 +50,12 @@
       $service_hasrestart     = true
       $service_hasstatus      = true
 
+      if $::operatingsystemmajrelease == 7 {
+        $default_config_file    = 'rsyslog_default'
+      }
+      else {
+        $default_config_file    = 'rsyslog_default-8'
+      }
     }
     redhat: {
       if $::operatingsystem == 'Amazon' {


The file rsyslog_default-8 is simply rsyslog_default but with 'RSYSLOGD_OPTIONS=""'.

**Comment by oznah** [comment]
I'm still having problems here. On a rhel 7 box I get this error.

```
change from stopped to running failed: Could not start Service[rsyslog]: Execution of '/usr/bin/systemctl start rsyslog' returned 1: Job for rsyslog.service failed. See 'systemctl status rsyslog.service' and 'journalctl -xn' for details.	   /Stage[main]/Rsyslog::Service/Service[rsyslog]/ensure	/etc/puppetlabs/puppet/environments/production/modules/rsyslog/manifests/service.pp	18	2015-04-24 11:42 EDT
```

My code is very simple.

 ` class {'rsyslog::client': server => $base_rc_rsyslog_server}`, that's it.

Puppet run in debug isn't very helpful either.

```
Debug: Executing '/bin/systemctl is-active rsyslog'
Debug: Executing '/bin/systemctl is-enabled rsyslog'
Debug: Executing '/bin/systemctl start rsyslog'
Error: Could not start Service[rsyslog]: Execution of '/bin/systemctl start rsyslog' returned 1: Job for rsyslog.service failed. See 'systemctl status rsyslog.service' and 'journalctl -xn' for details.
Wrapped exception:
Execution of '/bin/systemctl start rsyslog' returned 1: Job for rsyslog.service failed. See 'systemctl status rsyslog.service' and 'journalctl -xn' for details.
Error: /Stage[main]/Rsyslog::Service/Service[rsyslog]/ensure: change from stopped to running failed: Could not start Service[rsyslog]: Execution of '/bin/systemctl start rsyslog' returned 1: Job for rsyslog.service failed. See 'systemctl status rsyslog.service' and 'journalctl -xn' for details.
```

**Comment by saz** [comment]
This is fixed in master and will be released soon.
