### ISSUE TITLE
No basic examples at all..

### ISSUE THREAD

**Issue by ksemaev** [saz/puppet-rsyslog#240]
Wasted whole day trying to get throurh all that code. Absolutely complicated, no links, no clue why sometimes it goes like this and sometiems like this. And hiera syntax is not working at all with that code.

**Comment by saz** [comment]
Maybe you can be a little bit more specific. There are examples in the README, which might be enough to get rsyslog up and running either as client, server or both.

If you think, that there should be an easier example, it would be great if you can shed some light on the problems you've got (e.g. what you've been trying to achieve) instead of just ranting around without any useful information...

Just remember: I'm maintaining this module in my free time...
